### ISSUE TITLE
[REQUEST] Add skip-links to tab index to improve a11y for keyboard navigation

### ISSUE THREAD

**Issue by kiledal** [oslokommune/bydelsfakta#166]
When using a keyboard to navigate, the user has to tab through the full geography list to reach the main content. 

By adding a 'skip to main content' option to the tab index the user can choose to skip this list.

**Comment by aulonm** [comment]
I've implemented https://github.com/vue-a11y/vue-skip-to to see if this is a possible solution we can live with, or if we should just implement it ourselves so we don't add another dependency to our code.
