### ISSUE TITLE
[REQUEST] Change variable and method names containing 'subpage' to 'topic'

### ISSUE THREAD

**Issue by kiledal** [oslokommune/bydelsfakta#21]
Minor enhancement suggestion to rename 'subpage' references to 'topic' for better consistency throughout the code (e.g. `selectedSubpage` --> `selectedTopic`)

**Comment by aulonm** [comment]
fixed here: https://github.com/oslokommune/bydelsfakta/commit/6fc1661410d0e448e5c0389189414a37eb4fd732
