### ISSUE TITLE
[BUG] Tooltip positioning in IE11

### ISSUE THREAD

**Issue by kiledal** [oslokommune/bydelsfakta#75]
On Internet Explorer the tooltips get wrong position. They seem to be positioned at the very top of the SVG. 

**To Reproduce**
1. Go to a bar chart
2. Use the mouse to hover a bar
3. See error

**Expected behavior**
Tooltips should get positioned right above the cursor.

**Desktop:**
 - OS: Windows
 - Browser: Internet Explorer
 - Version: 11

**Smartphone:**
Not applicable on mobile.

**Additional context**
Might be related to d3.event's mouse position capture.

**Comment by aulonm** [comment]
Fixed #83
